apiVersion: v1
kind: Service
metadata:
  name: magic-service
  labels:
    app: magic-service
spec:
  clusterIP: None
  selector:
    app: magic-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic-service
  labels:
    app: magic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magic-service
  template:
    metadata:
      labels:
        app: magic-service
    spec:
      containers:
      - name: magic-service
        image: magic-service
        ports:
        - containerPort: 8090
